Repository JohnTitor/tsuncon, pull requests merged in 2019-02, with the labels that each got.

#14 docs: Remove unnecessary dollar signs
  README.md
Labels: S-awaiting-merge

#15 test: Remove branch config
  .circleci/config.yml
Labels: S-awaiting-merge

#17 minor: ningen ha oroka
  tsuncon.go
Labels: S-awaiting-review

#16 DeepWebUnderground
  tsuncon.go
Labels: S-do-not-merge
